### PR TITLE
Mnaveau/build xacro on build

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."

Should make so that the urdfs are rebuild at build-time.
Is compatible with the pip install system.

## How I Tested

[//]: # "Explain how you tested your changes"

I used the colcon system.
to be checked with the pip install.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [ ] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [ ] All new functions/classes are documented and existing documentation is updated according to changes.
- [ ] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Review by huaijiangzhu — COMMENTED** [review]
I see following errors when installing with pip. This is likely caused by ```_build_xacro()``` being called before xacro gets installed.  This error does not show up if xacro is already installed. Any ways to remediate this?
```
Building wheels for collected packages: robot-properties-bolt
  Building wheel for robot-properties-bolt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/setup.py'"'"'; __file__='"'"'/private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-wheel-okbmubec
       cwd: /private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/
  Complete output (39 lines):
  /usr/local/lib/python3.9/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
    warnings.warn(
  /usr/local/lib/python3.9/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/setup.py", line 157, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/setup.py", line 151, in run
      self._build_xacro()
    File "/private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/setup.py", line 110, in _build_xacro
      self._build_single_xacro_file(xacro_file, generated_urdf_path)
    File "/private/var/folders/2h/ffg5m1_11g9fj0b560vnjcmc0000gn/T/pip-req-build-u4i0wu9j/setup.py", line 113, in _build_single_xacro_file
      from xacro import process_file, open_output
  ModuleNotFoundError: No module named 'xacro'
  ----------------------------------------
  ERROR: Failed building wheel for robot-properties-bolt
  Running setup.py clean for robot-properties-bolt
Failed to build robot-properties-bolt
```

**Comment by MaximilienNaveau** [comment]
Weird, on my laptop, xacro is installed before the build goes on...

**Comment by MaximilienNaveau** [comment]
@huaijiangzhu what did you do to install it?
I did:
```
cd robot_properties_bolt
pip install .
```

**Review by Lhumd — APPROVED** [review]

**Comment by huaijiangzhu** [comment]
> @huaijiangzhu what did you do to install it?
> I did:
> 
> ```
> cd robot_properties_bolt
> pip install .
> ```

The same, though on mac. I tested it again on Ubuntu 18.04 and I see similar error messages. But the package did get installed successfully. It looks like setup.py got called another time with deprecated install method, but it will be gone after pip 21.0

Here is the deprecation warning:
```
 DEPRECATION: robot-properties-bolt was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

Here is the whole error message:
```
Building wheels for collected packages: robot-properties-bolt
  Building wheel for robot-properties-bolt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yl853c1w/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-yl853c1w/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mnjp0zkw                                                             
       cwd: /tmp/pip-req-build-yl853c1w/                                                                        
  Complete output (77 lines):                                                                                   
  /usr/local/lib/python3.6/dist-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead                
    % (opt, underscore_opt))                                                                                    
  /usr/local/lib/python3.6/dist-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead      
    % (opt, underscore_opt))                                                                                    
  running bdist_wheel                                                                                           
  running build                                                                                                 
  running build_py                                                                                              
  /usr/local/lib/python3.6/dist-packages/sphinxcontrib/moderncmakedomain/__init__.py:3: RemovedInSphinx40Warning: The alias 'sphinx.util.pycompat.htmlescape' is deprecated, use 'html.escape' instead. Check CHANGES for Sphinx API modifications.                                                                                             
    from .cmake import setup                                                                                    
  /usr/local/lib/python3.6/dist-packages/sphinxcontrib/moderncmakedomain/__init__.py:3: RemovedInSphinx40Warning: The alias 'sphinx.builders.qthelp.QtHelpBuilder' is deprecated, use 'sphinxcontrib.qthelp.QtHelpBuilder' instead. Check CHANGES for Sphinx API modifications.                                                                 
    from .cmake import setup                                                                                    
  /usr/local/lib/python3.6/dist-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document                                                                                                          
    warn("Container node skipped: type={0}".format(mdnode.t))                                                   
  /tmp/pip-req-build-yl853c1w/build/lib/robot_properties_bolt/doc/readme.md: WARNING: document isn't included in any toctree                                                                                                    
  /tmp/pip-req-build-yl853c1w/build/lib/robot_properties_bolt/doc/index.rst: WARNING: self referenced toctree found. Ignored.                                                                                                   
  /tmp/pip-req-build-yl853c1w/build/lib/robot_properties_bolt/doc/index.rst: WARNING: circular toctree references detected, ignoring: index <- index                                                                            
  sphinx-apidoc output:                                                                                         
   Running Sphinx v3.2.1                                                                                        
  making output directory... done                                                                               
  loading intersphinx inventory from https://docs.python.org/objects.inv...                                     
  intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv 
  building [mo]: targets for 0 po files that are out of date                                                    
  building [html]: targets for 2 source files that are out of date                                              
  updating environment: [new config] 2 added, 0 changed, 0 removed                                              
  reading sources... [ 50%] index                                                                               
  reading sources... [100%] readme                                                                              
                                                                                                                
  looking for now-outdated files... none found                                                                  
  pickling environment... done                                                                                  
  checking consistency... done                                                                                  
  preparing documents... done                                                                                   
  writing output... [ 50%] index                                                                                
  writing output... [100%] readme                                                                               
                                                                                                                
  generating indices...  genindexdone                                                                           
  writing additional pages...  searchdone                                                                       
  copying static files... ... done                                                                              
  copying extra files... done                                                                                   
  dumping search index in English (code: en)... done                                                            
  dumping object inventory... done                                                                              
  build succeeded, 3 warnings.                                                                                  
                                                                                                                
  The HTML pages are in html.                                                                                   
                                                                                                                
  sphinx-apidoc error:                                                                                          
   None                                                                                                         
  Traceback (most recent call last):                                                                            
    File "<string>", line 1, in <module>                                                                        
    File "/tmp/pip-req-build-yl853c1w/setup.py", line 186, in <module>                                          
      cmdclass={"build_py": custom_build_py},                                                                   
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup                    
      return distutils.core.setup(**attrs)                                                                      
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup                                             
      dist.run_commands()                                                                                       
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands                                      
      self.run_command(cmd)                                                                                     
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command                                       
      cmd_obj.run()                                                                                             
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run                                
      self.run_command('build')                                                                                 
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command                                        
      self.distribution.run_command(command)                                                                    
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command                                       
      cmd_obj.run()                                                                                             
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-yl853c1w/setup.py", line 149, in run
      self._build_xacro()
    File "/tmp/pip-req-build-yl853c1w/setup.py", line 110, in _build_xacro
      self._build_single_xacro_file(xacro_file, generated_urdf_path)
    File "/tmp/pip-req-build-yl853c1w/setup.py", line 113, in _build_single_xacro_file
      from xacro import process_file, open_output
  ModuleNotFoundError: No module named 'xacro'
  ----------------------------------------
  ERROR: Failed building wheel for robot-properties-bolt
  Running setup.py clean for robot-properties-bolt
Failed to build robot-properties-bolt
Installing collected packages: xacro, robot-properties-bolt
    Running setup.py install for robot-properties-bolt ... done
  DEPRECATION: robot-properties-bolt was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed robot-properties-bolt-1.0.0 xacro-1.13.3
WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Pull request merged**
